monitor.bluez.rules = [
    {
        matches = [
            { node.name = "~bluez_output.*" }
        ]
        actions = {
            update-props = {
                node.latency-offset-msec = 100
            }
        }
    }
]
