use_default_settings: true
server:
    secret_key: "x"
    limiter: true
valkey:
  url: unix:///run/valkey/valkey.sock?password=&db=1
checker:
    scheduling:
    start_after: [300, 1800]  # delay to start the first run of the checker
    every: [86400, 90000]     # how often the checker runs
search:
  safe_search: 2
  autocomplete: ""
  default_lang: "en"
  formats:
    - html
    - json
