# use pidof to prevent multiple instances if hyprland is restarted

exec-once = renice -n -20 -p $$

exec-once = pidof hypridle || hypridle
exec-once = pidof hyprpaper || hyprpaper
exec-once = pidof waybar || ~/.local/bin/waystarter.sh

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = easyeffects --hide-window --service-mode
#exec-once = foot --server

exec-once = ~/.local/bin/mktmp.sh
