misc:background_color = 0x191326

$opacity_inactive = 0.95
$opacity_floating = 0.85

$inner_gap = 5
$outer_gap = 10
env = HYPR_INNER_GAP,$inner_gap
env = HYPR_OUTER_GAP,$outer_gap

general {
	gaps_in = $inner_gap
	gaps_out = $outer_gap

	border_size = 0
}

decoration {
	rounding = 10
	rounding_power = 2

	inactive_opacity = $opacity_inactive
	dim_strength = 0.8

	shadow {
		enabled = false
	}

	blur {
		enabled = false
	}
}

animations {
	enabled = false
}
