-- Colorscheme generated by https://github.com/arcticlimer/djanho
-- originally from https://github.com/nodlag/godot-theme-vscode

local vim = vim
vim.cmd[[highlight clear]]
local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color3 = '#89E2FC'
local Color7 = '#E0E0E0'
local Color11 = '#222427'
local Color13 = '#623e45'
local Color8 = '#B1C8FA'
local Color15 = '#2C2E32'
local Color10 = '#CDCFD2'
local Color12 = '#2e3b41'
local Color14 = '#A7C1AA'
local Color4 = '#82FBC6'
local Color6 = '#F9ECA8'
local Color0 = '#EE7987'
local Color5 = '#cc8fe3'
local Color2 = '#B7FDE2'
local Color1 = '#76787D'
local Color9 = '#3E4246'

highlight('Error', nil, Color0, nil)
highlight('Comment', nil, Color1, nil)
highlight('Constant', nil, Color2, nil)
highlight('Function', nil, Color3, nil)
highlight('Keyword', nil, Color0, nil)
highlight('Type', nil, Color0, nil)
highlight('Type', nil, Color4, 'italic')
highlight('Conditional', nil, Color5, nil)
highlight('Repeat', nil, Color5, nil)
highlight('String', nil, Color6, nil)
highlight('Identifier', nil, Color7, nil)
highlight('Operator', nil, Color8, nil)
highlight('StatusLine', Color7, Color9, nil)
highlight('WildMenu', Color11, Color10, nil)
highlight('Pmenu', Color11, Color10, nil)
highlight('PmenuSel', Color10, Color9, nil)
highlight('PmenuThumb', Color11, Color10, nil)
highlight('DiffAdd', Color12, nil, nil)
highlight('DiffDelete', Color13, nil, nil)
highlight('Normal', Color11, Color10, nil)
highlight('Visual', Color9, nil, nil)
highlight('CursorLine', Color9, nil, nil)
highlight('ColorColumn', Color9, nil, nil)
highlight('SignColumn', Color11, nil, nil)
highlight('LineNr', nil, Color14, nil)
highlight('TabLine', Color15, Color1, nil)
highlight('TabLineSel', Color7, Color9, nil)
highlight('TabLineFill', Color15, Color1, nil)
highlight('TSPunctDelimiter', nil, Color10, nil)

link('TSString', 'String')
link('TSFunction', 'Function')
link('TSTag', 'MyTag')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('NonText', 'Comment')
link('TSType', 'Type')
link('TSOperator', 'Operator')
link('TSRepeat', 'Repeat')
link('TSNumber', 'Number')
link('TSPunctBracket', 'MyTag')
link('Folded', 'Comment')
link('TelescopeNormal', 'Normal')
link('TSConditional', 'Conditional')
link('TSProperty', 'TSField')
link('TSFuncMacro', 'Macro')
link('TSFloat', 'Number')
link('Operator', 'Keyword')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('Conditional', 'Operator')
link('Macro', 'Function')
link('TSComment', 'Comment')
link('TSTagDelimiter', 'Type')
link('Whitespace', 'Comment')
link('TSParameterReference', 'TSParameter')
link('TSConstant', 'Constant')
link('TSField', 'Constant')
link('TSLabel', 'Type')
link('TSNamespace', 'TSType')
link('TSParameter', 'Constant')
link('Repeat', 'Conditional')
link('CursorLineNr', 'Identifier')
link('TSKeyword', 'Keyword')
