pulse.rules = [
    {
        matches = [
            {
                application.process.binary = "spotify"
            }
        ]
        actions = {
            update-props = {
                node.name        = "SpotifyCustom"
                node.description = "Spotify"
                target.object    = "easyeffects_sink"
            }
        }
    }
]
