# .config/pipewire/pipewire-pulse.conf.d/tidal-fix.conf

pulse.rules = [
    {
        matches = [
            {
                application.process.binary = "tidal-hifi"
            }
        ]
        actions = {
            update-props = {
                node.name        = "TidalCustom"
                node.description = "Tidal Hi-Fi"
                # note: if target.object was working before, keep it,
                # but if it causes issues, we can try routing via
                # node.name in easyeffects instead.
                target.object    = "easyeffects_sink"
            }
        }
    }
]
