pulse.rules = [
    {
        matches = [
            {
                # matches the flatpak application id
                pipewire.access.portal.app_id = "com.mastermindzh.tidal-hifi"
            }
        ]
        actions = {
            update-props = {
                # this is what easyeffects looks for
                node.name        = "TidalCustom"
                node.description = "Tidal Hi-Fi"
				target.object    = "easyeffects_sink"
            }
        }
    }
]
